App\Entity\Produit:
    type: entity
    table: produit
    indexes:
        fk_produit_id_categorie:
            columns:
                - id_categorie
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        titre:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        prix:
            type: float
            nullable: false
            precision: 10
            scale: 0
        image:
            type: string
            nullable: false
            length: 10
            options:
                fixed: false
        description:
            type: string
            nullable: false
            length: 300
            options:
                fixed: false
    manyToOne:
        idCategorie:
            targetEntity: Categorie
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_categorie:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
